### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by gstenzel** [kdschlosser/nvapi#1]
I´m getting a WinError 126 (`The specified module could not be found`).
Steps to reproduce:
1. Cloned from this repo
1. Compiled nvapi.dll
1. In Python: `import nvapi`
OS: Current Windows 10
Could this be an path issue (because of Windows´ `\` pathes)? Or did I not install something correctly?

**Comment by kdschlosser** [comment]
There is no setup.py file for this library so you need to clone the library and download it as a zip file. Open the zip file up and extract only the nvapi folder into the site-packages folder of your python installation.

You do not need to compile anything or replace anythin in the library, I already compiled a special version of the DLL in order for it to work. I used the latest Windows 10 SKD at the time. so it should not have an issue.

Windows works with both `\` and `/` in anything path related.
I would also like to see the entire traceback

**Comment by gstenzel** [comment]
Error persists:
```python
>>> import nvapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXX\AppData\Roaming\Python\Python37\site-packages\nvapi\__init__.py", line 59, in <module>
    from .nvapi_h import *
  File "C:\Users\XXX\AppData\Roaming\Python\Python37\site-packages\nvapi\nvapi_h.py", line 16590, in <module>
    from .dx.d3d11_h import *
  File "C:\Users\XXX\AppData\Roaming\Python\Python37\site-packages\nvapi\dx\d3d11_h.py", line 7573, in <module>
    from .d3d10_1_h import * # NOQA
  File "C:\Users\XXX\AppData\Roaming\Python\Python37\site-packages\nvapi\dx\d3d10_1_h.py", line 264, in <module>
    rdpd3d = ctypes.windll.RDPD3D
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in __getattr__
    dll = self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
I recompiled it because I don´t really like precompiled `.dll`s :) .
Also, windows DOES have a problem with `\`: [Stackoverflow with similar problem](https://stackoverflow.com/a/6087086)

**Comment by kdschlosser** [comment]
the problem you are having is not with the nvapi.dll file. you are missing a file in Windows.

RDPD3D.dll is missing.  

No Windows does not have a problem with `\` in Python the `\` is an escape character. This is the reason why the solution you see on stack overflow states to us a raw string or double backslashes or forward slashes. a raw string turns off the use of escape characters a double back slash is escaping the backslash and using forward slashes is a way around the backslash problem because Windows allows the user of forward slashes in paths

It's moot anywho because I am not using any path statements to load the dll. as can be seen here `rdpd3d = ctypes.windll.RDPD3D`, No slashes.

also the nvapi.dll file needs to be compiled in a very specific way in order for it to work properly, otherwise I would not have included precompiled with the library I would have left it up to the user to do.

the RDPD3D.dll file is supposed to reside in your windows/system32 folder If you do not have it I would try reinstalling DirectX on your system. there are reports of virus scanning programs and malware removal tools deleting this file.

**Comment by gstenzel** [comment]
Found a (for me) better solution. Thanks anyway.
